apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-nodejs-app-s5wh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-nodejs-app-s5wh
    app.kubernetes.io/part-of: nodejs-users
  name: simple-nodejs-app-s5wh
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: simple-nodejs-app-s5wh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: simple-nodejs-app-s5wh
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/e2e-demos-ttfc-tenant/nodejs-users/simple-nodejs-app-s5wh@sha256:e3b38dd1001cf0772f707133b69fa5a58cbfd4aca373761e384f83bd9f2f3b1d
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
